from typing import Dict
from backend_service.app.domain.models.saathi import (
    CustomerRelationship,
    ClientTier,
    TransitionStatus,
    CRMInteraction,
    TransitionActionItem,
    ActionPriority,
    ActionStatus,
    RelationshipBrief,
    CustomerFeedback,
)


def get_saathi_seed_data() -> Dict[str, CustomerRelationship]:
    """
    Returns initial high-fidelity relationship profiles representing Axis Bank
    Burgundy, NRI Elite, and Burgundy Private wealth clients.
    """
    c1 = CustomerRelationship(
        id="cust-nri-rahul-sharma",
        name="Rahul Sharma",
        tier=ClientTier.NRI_ELITE,
        segment_description="NRI Elite Wealth — Global Indian Banking",
        city="Singapore / Gurgaon",
        account_number_masked="•••• 8492",
        aum_display="₹4.85 Cr ($580K USD)",
        tenure_years=7,
        avatar_color="from-amber-600 to-rose-700",
        previous_rm_name="Kunal Deshmukh",
        previous_rm_role="VP, NRI Banking & Global Wealth",
        transfer_reason="Promoted to Regional Head of Wealth (ASEAN)",
        new_rm_name="Neha Kapoor",
        new_rm_role="Senior Wealth Partner, NRI & Burgundy",
        new_rm_phone="+91 98201 44821",
        new_rm_email="neha.kapoor@axisbank.com",
        status=TransitionStatus.CUSTOMER_REVIEW,
        transition_date="2026-09-02",
        interactions=[
            CRMInteraction(
                id="int-101",
                date="2026-08-18",
                channel="Phone Call",
                rm_name="Kunal Deshmukh",
                summary="Discussed daughter Ananya's upcoming move to London for MSc Data Science at UCL. Needs streamlined LRS remittance process for university tuition fees and living expenses. Reminded him about the A2 declaration forms.",
                tags=["Family", "Education", "Remittance", "LRS"],
            ),
            CRMInteraction(
                id="int-102",
                date="2026-08-04",
                channel="WhatsApp Note",
                rm_name="Kunal Deshmukh",
                summary="Rahul mentioned his father Ashok (78) in DLF Phase 5 Gurgaon needs assistance with physical cash withdrawal and Form 15H submission. Requested Gurgaon branch RM visit before end of quarter.",
                tags=["Parents", "Doorstep Banking", "Gurgaon", "Tax"],
            ),
            CRMInteraction(
                id="int-103",
                date="2026-07-22",
                channel="Branch Meeting",
                rm_name="Kunal Deshmukh",
                summary="Annual portfolio and home loan review. The ₹1.85 Cr home loan on Gurgaon penthouse has rate reset scheduled for end of September. Customer is sensitive to spread changes and requested benchmark rate discount review.",
                tags=["Home Loan", "ROI Reset", "Portfolio", "Real Estate"],
            ),
            CRMInteraction(
                id="int-104",
                date="2026-06-15",
                channel="Email Summary",
                rm_name="Kunal Deshmukh",
                summary="Preference reminder: Customer works in Singapore hedge fund (UTC+8). Strictly prefers calls between 6:30 PM - 8:30 PM IST on weekdays. Do not send SMS alerts for marketing campaigns.",
                tags=["Preferences", "Time Zone", "Channel Nuance"],
            ),
        ],
        action_items=[
            TransitionActionItem(
                id="act-101",
                title="Home Loan Annual ROI Reset Review",
                description="Review current benchmark spread on ₹1.85 Cr Gurgaon loan and apply relationship discount before Sept 30 reset.",
                category="Loan Renewal",
                priority=ActionPriority.HIGH,
                status=ActionStatus.PENDING,
                sla_date="2026-09-25",
                assigned_to="Neha Kapoor",
            ),
            TransitionActionItem(
                id="act-102",
                title="Overseas Student Remittance Setup (UCL London)",
                description="Coordinate with NRI Desk to pre-approve A2 form and fee remittance package for daughter Ananya's tuition.",
                category="Education & Forex",
                priority=ActionPriority.HIGH,
                status=ActionStatus.IN_PROGRESS,
                sla_date="2026-09-18",
                assigned_to="Neha Kapoor",
            ),
            TransitionActionItem(
                id="act-103",
                title="Doorstep Banking for Parents in DLF Gurgaon",
                description="Schedule Gurgaon branch service officer visit to parents' home for doorstep banking and Form 15H collection.",
                category="Senior Citizen Care",
                priority=ActionPriority.MEDIUM,
                status=ActionStatus.PENDING,
                sla_date="2026-09-22",
                assigned_to="Neha Kapoor",
            ),
        ],
        brief=RelationshipBrief(
            client_sentiment="Highly loyal, long-standing client (7 years). Values proactive follow-through on family commitments over aggressive product pitching.",
            executive_summary="Rahul is an institutional finance professional in Singapore who relies heavily on Axis for both his global cross-border wealth and his family's domestic banking in India. Core priorities are his daughter's education financing in the UK, elderly parents' doorstep banking in Gurgaon, and an upcoming home loan rate reset.",
            family_and_lifestage=[
                "Daughter Ananya moving to London (UCL) for MSc Data Science in October 2026.",
                "Elderly parents Ashok (78) & Savitri (74) living in DLF Phase 5, Gurgaon — need doorstep banking.",
            ],
            preferences_and_nuances=[
                "Prefers voice calls between 6:30 PM – 8:30 PM IST on weekdays (aligned with Singapore UTC+8).",
                "Appreciates WhatsApp for urgent heads-up; dislikes generic SMS marketing.",
                "Highly numbers-driven and detail-oriented; expects clear cost-benefit breakdowns.",
            ],
            active_portfolio_summary="₹4.85 Cr AUM across NRE/NRO FDs, Axis Bluechip Mutual Fund SIPs, and ₹1.85 Cr Home Loan (Gurgaon).",
            key_discussion_topics=[
                "Daughter's UK tuition remittance and living expenses structure.",
                "Home loan rate reset and repo-spread benchmark review.",
                "Senior citizen doorstep banking for parents.",
            ],
            conversation_starter="Hello Rahul, Neha Kapoor here from Axis Bank. Kunal has briefed me thoroughly on our journey together over the past 7 years. I understand Ananya is preparing for her move to UCL in London, your parents in Gurgaon need doorstep assistance, and we have the home loan rate reset due this month. I have already initiated the overseas student remittance documentation so you won't have to restart anything. Let me take this forward together.",
            talking_points=[
                "Confirm UCL tuition deadline and provide pre-filled LRS documentation.",
                "Share the reduced rate reset options for the Gurgaon property.",
                "Confirm that Gurgaon branch lead has been assigned for doorstep parents' visit.",
            ],
            synthesized_at="2026-09-02T14:30:00Z",
        ),
        feedback=CustomerFeedback(
            confirmed_at=None,
            customer_notes=None,
            corrected_items=[],
            has_verified=False,
        ),
    )

    c2 = CustomerRelationship(
        id="cust-burgundy-dr-sen",
        name="Dr. Ananya Sen",
        tier=ClientTier.BURGUNDY_PRIVATE,
        segment_description="Burgundy Private — Family Office & Ultra HNW",
        city="South Mumbai (Altamount Road)",
        account_number_masked="•••• 3190",
        aum_display="₹18.5 Cr ($2.2M USD)",
        tenure_years=11,
        avatar_color="from-rose-800 to-purple-950",
        previous_rm_name="Vikram Singhania",
        previous_rm_role="Director, Burgundy Private Client Group",
        transfer_reason="Resigned to join a venture capital partnership",
        new_rm_name="Aditya Mehta",
        new_rm_role="Vice President, Burgundy Private Wealth",
        new_rm_phone="+91 99200 88123",
        new_rm_email="aditya.mehta@axisbank.com",
        status=TransitionStatus.INITIATED,
        transition_date="2026-09-05",
        interactions=[
            CRMInteraction(
                id="int-201",
                date="2026-08-28",
                channel="In-Person Lunch",
                rm_name="Vikram Singhania",
                summary="Discussed allocation of ₹3.5 Cr proceeds from healthtech angel exit. Exploring Axis Burgundy Private Discretionary PMS (Multi-Cap Opportunities). Client wants capital protection with moderate equity upside.",
                tags=["PMS", "Liquidity Event", "Private Wealth", "Angel Exit"],
            ),
            CRMInteraction(
                id="int-202",
                date="2026-08-10",
                channel="WhatsApp Note",
                rm_name="Vikram Singhania",
                summary="Dr. Sen mentioned her surgical schedule is intense between Mon-Fri (7 AM to 4 PM). Strictly do not call during hospital hours. Saturday mornings between 10 AM - 11:30 AM are ideal for wealth discussions.",
                tags=["Communication Rules", "Surgical Schedule", "High Respect"],
            ),
            CRMInteraction(
                id="int-203",
                date="2026-07-14",
                channel="Branch Meeting",
                rm_name="Vikram Singhania",
                summary="Discussed Sen Family Trust deed registration with Axis Trustee Services. Client needs final legal opinion on inheritance tax sheltering.",
                tags=["Trustee Services", "Estate Planning", "Succession"],
            ),
        ],
        action_items=[
            TransitionActionItem(
                id="act-201",
                title="Burgundy Private PMS Allocation Proposal",
                description="Prepare customized mandate document for ₹3.5 Cr discretionary PMS investment with drawdown schedule.",
                category="Wealth Allocation",
                priority=ActionPriority.HIGH,
                status=ActionStatus.PENDING,
                sla_date="2026-09-20",
                assigned_to="Aditya Mehta",
            ),
            TransitionActionItem(
                id="act-202",
                title="Axis Trustee Legal Opinion Follow-Up",
                description="Obtain formal legal sign-off on Sen Family Trust clauses from Axis Trustee Services and deliver to client.",
                category="Estate & Trust",
                priority=ActionPriority.HIGH,
                status=ActionStatus.IN_PROGRESS,
                sla_date="2026-09-28",
                assigned_to="Aditya Mehta",
            ),
        ],
        brief=RelationshipBrief(
            client_sentiment="Ultra-HNW medical pioneer. Deep emotional attachment to 11-year relationship with Axis. Sensitive to interruptions during medical commitments.",
            executive_summary="Dr. Sen is a renowned surgical oncologist and medical tech founder with ₹18.5 Cr AUM. Following a recent ₹3.5 Cr liquidity event, she is evaluating discretionary PMS and formalizing estate succession via Axis Trustee Services. Respect for her demanding schedule and discreet, proactive execution are paramount.",
            family_and_lifestage=[
                "Founder of MedTech startup with recent secondary exit.",
                "Structuring Sen Family Trust for second-generation succession.",
            ],
            preferences_and_nuances=[
                "Strict 'Do Not Disturb' policy Mon–Fri 7:00 AM – 4:00 PM due to hospital OT schedule.",
                "Saturday mornings (10:00 AM – 11:30 AM) preferred for wealth reviews.",
                "Prefers concise executive summaries over verbose product brochures.",
            ],
            active_portfolio_summary="₹18.5 Cr AUM spanning Fixed Income, Alternate Investment Funds (AIF Cat II), and Direct Equity.",
            key_discussion_topics=[
                "₹3.5 Cr PMS Mandate allocation & fee structure.",
                "Sen Family Trust legal registration with Axis Trustee Services.",
            ],
            conversation_starter="Good morning Dr. Sen, Aditya Mehta here from Axis Burgundy Private. Vikram shared a thorough overview of your 11-year relationship with Axis before his transition. I am fully updated on the ₹3.5 Cr PMS allocation from your recent exit and the Axis Trustee opinion for your family trust. Because I know your surgery schedule takes absolute precedence during weekdays, I would be glad to connect briefly this Saturday at 10 AM or whenever convenient for you.",
            talking_points=[
                "Acknowledge the 11-year trust with Axis Burgundy Private.",
                "Present the completed legal opinion on the family trust.",
                "Review the draft PMS portfolio allocation at her convenience.",
            ],
            synthesized_at="2026-09-05T11:00:00Z",
        ),
        feedback=CustomerFeedback(
            confirmed_at=None,
            customer_notes=None,
            corrected_items=[],
            has_verified=False,
        ),
    )

    c3 = CustomerRelationship(
        id="cust-wealth-vikram-malhotra",
        name="Vikramaditya Malhotra",
        tier=ClientTier.WEALTH,
        segment_description="Axis Wealth & Commercial Banking",
        city="New Delhi (Aerocity / Vasant Vihar)",
        account_number_masked="•••• 7104",
        aum_display="₹7.20 Cr ($860K USD)",
        tenure_years=5,
        avatar_color="from-teal-700 to-slate-900",
        previous_rm_name="Pooja Bansal",
        previous_rm_role="AVP, Commercial & Wealth Banking",
        transfer_reason="Relocated to Axis Bangalore Innovation Hub",
        new_rm_name="Rajesh Verma",
        new_rm_role="Director, Wealth & Enterprise Client Solutions",
        new_rm_phone="+91 98110 32901",
        new_rm_email="rajesh.verma@axisbank.com",
        status=TransitionStatus.CUSTOMER_CONFIRMED,
        transition_date="2026-08-25",
        interactions=[
            CRMInteraction(
                id="int-301",
                date="2026-08-20",
                channel="Coffee Meeting (Aerocity)",
                rm_name="Pooja Bansal",
                summary="Vikram is expanding his logistics tech firm to Dubai (DIFC). Needs multi-currency corporate travel card for 8 executives and credit line enhancement of ₹2.5 Cr for export receivables.",
                tags=["Export Finance", "Dubai Expansion", "Forex Card", "SME"],
            ),
            CRMInteraction(
                id="int-302",
                date="2026-08-01",
                channel="Email Summary",
                rm_name="Pooja Bansal",
                summary="High-speed communicator. Prefers bullet points and immediate turnarounds. Family: son Kabir is preparing for US college entrance exams.",
                tags=["Preferences", "Fast Turnaround", "Family"],
            ),
        ],
        action_items=[
            TransitionActionItem(
                id="act-301",
                title="Corporate Multi-Currency Forex Card Issuance",
                description="Deliver 8 multi-currency cards with preloaded AED and USD limits for executive team Dubai delegation.",
                category="Forex & Commercial",
                priority=ActionPriority.HIGH,
                status=ActionStatus.COMPLETED,
                sla_date="2026-09-08",
                assigned_to="Rajesh Verma",
            ),
            TransitionActionItem(
                id="act-302",
                title="Commercial Credit Line (₹2.5 Cr) Sanction Letter",
                description="Coordinate with commercial risk committee for enhanced overdraft facility against export invoices.",
                category="Credit Enhancement",
                priority=ActionPriority.HIGH,
                status=ActionStatus.IN_PROGRESS,
                sla_date="2026-09-15",
                assigned_to="Rajesh Verma",
            ),
        ],
        brief=RelationshipBrief(
            client_sentiment="Fast-moving growth entrepreneur. Values banking agility, quick TAT, and unified handling of personal wealth and business accounts.",
            executive_summary="Vikramaditya is the founder of a high-growth logistics technology enterprise scaling into the GCC. He balances active personal investments (₹7.2 Cr AUM) with heavy commercial banking needs. Core requirements are export credit enhancement and smooth forex solutions for his team.",
            family_and_lifestage=[
                "Son Kabir in grade 12, preparing for US university admissions.",
                "Business expanding into Dubai International Financial Centre (DIFC).",
            ],
            preferences_and_nuances=[
                "Direct, concise bullet-point communications; prefers rapid email/WhatsApp responses.",
                "Frequent flyer between Delhi, Dubai, and Bangalore.",
            ],
            active_portfolio_summary="₹7.2 Cr personal AUM + ₹15 Cr commercial banking turnover through Axis current accounts.",
            key_discussion_topics=[
                "₹2.5 Cr credit limit enhancement for export receivables.",
                "Executive multi-currency forex cards for Dubai delegation.",
            ],
            conversation_starter="Hello Vikram, Rajesh Verma here. Pooja briefed me on our 5-year partnership before her move to Bangalore. I know you're in the midst of the Dubai DIFC expansion and the export credit limit enhancement is on critical path. I've already confirmed the multi-currency cards are dispatched, and I'm pushing the credit committee on the sanction letter today.",
            talking_points=[
                "Forex cards delivered to Aerocity office.",
                "Status update on ₹2.5 Cr credit enhancement.",
                "Schedule quick 10-minute catchup at Aerocity.",
            ],
            synthesized_at="2026-08-26T09:15:00Z",
        ),
        feedback=CustomerFeedback(
            confirmed_at="2026-08-27T10:14:00Z",
            customer_notes="Confirmed. Please also note that Kabir's SAT coaching fees might require a direct wire transfer to Singapore test center by next Wednesday.",
            corrected_items=["Added son Kabir's test fee wire transfer deadline."],
            has_verified=True,
        ),
    )

    return {
        c1.id: c1,
        c2.id: c2,
        c3.id: c3,
    }
