from typing import Dict
from backend_service.app.domain.models.saathi import (
    CustomerRelationship,
    ClientTier,
    TransitionStatus,
    CRMInteraction,
    TransitionActionItem,
    ActionPriority,
    ActionStatus,
    CommitmentItem,
    CommitmentType,
    CommitmentStatus,
    RelationshipTimelineEvent,
    ContradictionAlert,
    CustomerFact,
    CustomerFactStatus,
    RelationshipHealth,
    HealthLevel,
    PreCallBriefing,
    ManagementSummary,
    RelationshipBrief,
    CustomerFeedback,
)


def get_saathi_seed_data() -> Dict[str, CustomerRelationship]:
    """
    Returns initial high-fidelity relationship profiles representing Axis Bank
    Burgundy, NRI Elite, and Burgundy Private wealth clients with complete
    relationship continuity memory.
    """
    c1 = CustomerRelationship(
        id="cust-nri-rahul-sharma",
        name="Rahul Sharma",
        tier=ClientTier.NRI_ELITE,
        segment_description="NRI Elite Wealth — Global Indian Banking",
        city="Singapore / Gurgaon",
        account_number_masked="•••• 8492",
        aum_display="₹4.85 Cr ($580K USD)",
        tenure_years=7,
        avatar_color="from-amber-600 to-rose-700",
        previous_rm_name="Kunal Deshmukh",
        previous_rm_role="VP, NRI Banking & Global Wealth",
        transfer_reason="Promoted to Regional Head of Wealth (ASEAN)",
        new_rm_name="Neha Kapoor",
        new_rm_role="Senior Wealth Partner, NRI & Burgundy",
        new_rm_phone="+91 98201 44821",
        new_rm_email="neha.kapoor@axisbank.com",
        status=TransitionStatus.CUSTOMER_REVIEW,
        transition_date="2026-09-02",
        interactions=[
            CRMInteraction(
                id="int-101",
                date="2026-08-18",
                channel="Phone Call",
                rm_name="Kunal Deshmukh",
                summary="Discussed daughter Ananya's upcoming move to London for MSc Data Science at UCL. Needs streamlined LRS remittance process for university tuition fees and living expenses. Reminded him about the A2 declaration forms. Customer also enquired whether any preferential forex margin is possible on tuition; Kunal clarified bank will review margins once tuition invoice is submitted, but no concession was promised.",
                tags=["Family", "Education", "Remittance", "LRS"],
            ),
            CRMInteraction(
                id="int-102",
                date="2026-08-04",
                channel="WhatsApp Note",
                rm_name="Kunal Deshmukh",
                summary="Rahul mentioned his father Ashok (78) in DLF Phase 5 Gurgaon needs assistance with physical cash withdrawal and Form 15H submission. Kunal committed that a Gurgaon branch officer will make a doorstep visit before end of quarter.",
                tags=["Parents", "Doorstep Banking", "Gurgaon", "Tax"],
            ),
            CRMInteraction(
                id="int-103",
                date="2026-07-22",
                channel="Branch Meeting",
                rm_name="Kunal Deshmukh",
                summary="Annual portfolio and home loan review. The ₹1.85 Cr home loan on Gurgaon penthouse has rate reset scheduled for end of September. Customer is sensitive to spread changes. Kunal explicitly promised to apply the Burgundy relationship spread discount of 25 bps prior to the Sept 30 reset.",
                tags=["Home Loan", "ROI Reset", "Portfolio", "Real Estate"],
            ),
            CRMInteraction(
                id="int-104",
                date="2026-06-15",
                channel="Email Summary",
                rm_name="Kunal Deshmukh",
                summary="Preference update: Customer works in Singapore hedge fund (UTC+8). Strictly prefers calls between 6:30 PM - 8:30 PM IST on weekdays. Do not send SMS alerts for marketing campaigns. Note that previously in 2023 he preferred morning email briefs.",
                tags=["Preferences", "Time Zone", "Channel Nuance"],
            ),
        ],
        action_items=[
            TransitionActionItem(
                id="act-101",
                title="Home Loan Annual ROI Reset Review",
                description="Review current benchmark spread on ₹1.85 Cr Gurgaon loan and apply relationship discount before Sept 30 reset.",
                category="Loan Renewal",
                priority=ActionPriority.HIGH,
                status=ActionStatus.PENDING,
                sla_date="2026-09-25",
                assigned_to="Neha Kapoor",
            ),
            TransitionActionItem(
                id="act-102",
                title="Overseas Student Remittance Setup (UCL London)",
                description="Coordinate with NRI Desk to pre-approve A2 form and fee remittance package for daughter Ananya's tuition.",
                category="Education & Forex",
                priority=ActionPriority.HIGH,
                status=ActionStatus.IN_PROGRESS,
                sla_date="2026-09-18",
                assigned_to="Neha Kapoor",
            ),
            TransitionActionItem(
                id="act-103",
                title="Doorstep Banking for Parents in DLF Gurgaon",
                description="Schedule Gurgaon branch service officer visit to parents' home for doorstep banking and Form 15H collection.",
                category="Senior Citizen Care",
                priority=ActionPriority.MEDIUM,
                status=ActionStatus.PENDING,
                sla_date="2026-09-22",
                assigned_to="Neha Kapoor",
            ),
        ],
        commitments=[
            CommitmentItem(
                id="com-101",
                title="25 bps Spread Discount on Gurgaon Home Loan",
                details="Kunal explicitly promised to submit the relationship spread concession approval to the Retail Asset Ops committee before the Sept 30 reset.",
                committed_by="Kunal Deshmukh",
                committed_on="2026-07-22",
                commitment_type=CommitmentType.CONFIRMED_COMMITMENT,
                status=CommitmentStatus.PENDING,
                urgency=ActionPriority.HIGH,
                source_interaction_id="int-103",
                evidence_snippet="Kunal explicitly promised to apply the Burgundy relationship spread discount of 25 bps prior to the Sept 30 reset.",
            ),
            CommitmentItem(
                id="com-102",
                title="Doorstep Banking & Form 15H Collection in Gurgaon",
                details="Committed that a branch relationship executive from DLF Gurgaon branch will visit father Ashok (78) at home for physical cash withdrawal and tax declaration.",
                committed_by="Kunal Deshmukh",
                committed_on="2026-08-04",
                commitment_type=CommitmentType.CONFIRMED_COMMITMENT,
                status=CommitmentStatus.PENDING,
                urgency=ActionPriority.MEDIUM,
                source_interaction_id="int-102",
                evidence_snippet="Kunal committed that a Gurgaon branch officer will make a doorstep visit before end of quarter.",
            ),
            CommitmentItem(
                id="com-103",
                title="Preferential Forex Margin on Tuition Remittance",
                details="Customer enquired about preferential forex markup on the UCL tuition payment. Discussed as a possibility subject to invoice submission, but no concession was booked or promised.",
                committed_by="Kunal Deshmukh",
                committed_on="2026-08-18",
                commitment_type=CommitmentType.DISCUSSED_POSSIBILITY,
                status=CommitmentStatus.PENDING,
                urgency=ActionPriority.MEDIUM,
                source_interaction_id="int-101",
                evidence_snippet="Customer also enquired whether any preferential forex margin is possible on tuition; Kunal clarified bank will review margins once tuition invoice is submitted, but no concession was promised.",
            ),
        ],
        timeline=[
            RelationshipTimelineEvent(
                id="time-101",
                year="2019",
                date_display="November 2019",
                title="Relationship Established",
                description="Opened NRE/NRO Premier savings account and booked inaugural ₹50L fixed deposit upon relocating to Singapore.",
                category="Relationship Inception",
                source_channel="Branch Onboarding",
            ),
            RelationshipTimelineEvent(
                id="time-102",
                year="2022",
                date_display="May 2022",
                title="Gurgaon Penthouse Home Loan Sanctioned",
                description="Disbursed ₹1.85 Cr home loan with benchmark-linked ROI for primary residential property in DLF Phase 5.",
                category="Credit & Lending",
                source_channel="Loan Operations",
            ),
            RelationshipTimelineEvent(
                id="time-103",
                year="2024",
                date_display="August 2024",
                title="NRI Elite Wealth Upgrade & Mutual Fund Portfolio",
                description="Upgraded to NRI Elite tier; initiated systematic mutual fund investments (Axis Bluechip & Multicap SIPs) totaling ₹1.2 Cr.",
                category="Wealth & Investment",
                source_channel="Annual Review",
            ),
            RelationshipTimelineEvent(
                id="time-104",
                year="2026",
                date_display="August 2026",
                title="Daughter Ananya's Overseas Education Planning",
                description="Initiated UCL London MSc education funding and Liberalised Remittance Scheme (LRS) structuring.",
                category="Family & Education",
                source_channel="Phone Call",
                interaction_id="int-101",
            ),
            RelationshipTimelineEvent(
                id="time-105",
                year="2026",
                date_display="September 2026",
                title="RM Transition: Kunal Deshmukh to Neha Kapoor",
                description="Kunal promoted to ASEAN Regional Head; handover activated under Saathi Continuity Engine.",
                category="Transition",
                source_channel="Saathi System",
            ),
        ],
        contradictions=[
            ContradictionAlert(
                id="contra-101",
                title="Communication Preference Shift",
                description="Earlier profile recorded email as primary channel. Recent WhatsApp interaction specifies strict voice calls between 6:30 PM - 8:30 PM IST.",
                detected_date="2026-08-18",
                previous_record="2023 CRM profile: 'Prefers weekly email summaries; avoids phone calls during market hours.'",
                recent_record="2026-06-15 Note: 'Strictly prefers voice calls between 6:30 PM - 8:30 PM IST (Singapore UTC+8); WhatsApp for urgent alerts.'",
                recommendation="Prioritize weekday evening voice calls (6:30 PM - 8:30 PM IST). Do not send cold morning emails or promotional SMS.",
            ),
        ],
        facts=[
            CustomerFact(
                id="fact-101",
                statement="Daughter Ananya is moving to London for MSc Data Science at University College London (UCL) in October 2026.",
                category="Family & Education",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-08-18",
            ),
            CustomerFact(
                id="fact-102",
                statement="Elderly parents Ashok (78) and Savitri (74) reside in DLF Phase 5 Gurgaon and require doorstep cash withdrawal & Form 15H tax filing.",
                category="Family Assistance",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-08-04",
            ),
            CustomerFact(
                id="fact-103",
                statement="Gurgaon Penthouse home loan (₹1.85 Cr) rate reset is scheduled for September 30, with a committed 25 bps spread discount review.",
                category="Financial Obligations",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-07-22",
            ),
            CustomerFact(
                id="fact-104",
                statement="Strict contact window: Weekday evenings 6:30 PM – 8:30 PM IST (aligned with Singapore UTC+8 hedge fund hours).",
                category="Preferences",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-06-15",
            ),
        ],
        health=RelationshipHealth(
            level=HealthLevel.ATTENTION_REQUIRED,
            headline="Attention Required: Critical Rate Reset & Tuition SLA within 18 days",
            reasons=[
                "Home loan rate reset deadline (Sept 30) requires 25 bps spread concession processing.",
                "Daughter's UCL tuition remittance deadline is approaching; pre-approval of A2 form is pending.",
                "Doorstep banking for elderly parents in Gurgaon has not yet been executed by the local branch.",
            ],
        ),
        pre_call_brief=PreCallBriefing(
            who_is_customer="Rahul Sharma, 7-year NRI Elite wealth client based in Singapore managing a hedge fund. Highly valued cross-border relationship (₹4.85 Cr AUM).",
            what_matters=[
                "Daughter Ananya's tuition remittance to UCL London without forex or regulatory delay.",
                "Dignified doorstep care and tax assistance for his elderly parents in Gurgaon.",
                "Proactive rate reset handling on his ₹1.85 Cr home loan.",
            ],
            current_discussions=[
                "LRS A2 declaration and outward remittance setup for UK tuition.",
                "Benchmark spread discount approval on Gurgaon property loan.",
            ],
            what_we_owe=[
                "25 bps spread discount submission before Sept 30 reset (Promised by Kunal).",
                "Assigned DLF branch officer for parents' doorstep banking visit.",
            ],
            unresolved_issues=[
                "No formal forex concession was booked for tuition; RM must clarify our competitive card/wire pricing without overpromising.",
            ],
            follow_up_items=[
                "Confirm that UCL student remittance documents are ready to sign.",
                "Provide written confirmation of home loan spread review status.",
            ],
            sensitive_nuances=[
                "Time zone: Singapore is UTC+8 (+2.5 hrs ahead of IST). Never call during India morning/afternoon.",
                "Hates pushy investment cross-sells; respects RMs who execute operational and family banking flawlessly.",
            ],
            recommended_approach="Lead directly with Ananya's UCL London remittance and the Gurgaon home loan discount. Reference Kunal warmly, acknowledge the transition, and reassure him that nothing will drop.",
        ),
        management_summary=ManagementSummary(
            client_snapshot="Rahul Sharma is a high-affinity NRI Elite client (₹4.85 Cr AUM, 7-year relationship). Both offshore global investments and onshore family banking are routed through Axis.",
            aum_and_tier="₹4.85 Cr AUM ($580K USD) • NRI Elite Tier • High Net Worth Individuals",
            active_opportunities=[
                "Overseas education loan / tuition forex flows (~₹45L annual volume).",
                "Repatriation portfolio reinvestment upon FD maturity in Q3.",
            ],
            risk_and_unresolved=[
                "Risk of friction if Gurgaon branch fails to deliver doorstep banking for parents.",
                "Ensure promised 25 bps home loan rate spread discount is honored before Sept 30.",
            ],
            rm_handover_status="Warm handover underway. AI brief generated, customer review dispatch queued, open SLAs assigned to Neha Kapoor.",
            executive_notes="Retaining Rahul is strategically vital for ASEAN wealth desk. All committed items must be tracked to completion before October.",
        ),
        brief=RelationshipBrief(
            client_sentiment="Highly loyal, long-standing client (7 years). Values proactive follow-through on family commitments over aggressive product pitching.",
            executive_summary="Rahul is an institutional finance professional in Singapore who relies heavily on Axis for both his global cross-border wealth and his family's domestic banking in India. Core priorities are his daughter's education financing in the UK, elderly parents' doorstep banking in Gurgaon, and an upcoming home loan rate reset.",
            family_and_lifestage=[
                "Daughter Ananya moving to London (UCL) for MSc Data Science in October 2026.",
                "Elderly parents Ashok (78) & Savitri (74) living in DLF Phase 5, Gurgaon — need doorstep banking.",
            ],
            preferences_and_nuances=[
                "Prefers voice calls between 6:30 PM – 8:30 PM IST on weekdays (aligned with Singapore UTC+8).",
                "Appreciates WhatsApp for urgent heads-up; dislikes generic SMS marketing.",
                "Highly numbers-driven and detail-oriented; expects clear cost-benefit breakdowns.",
            ],
            active_portfolio_summary="₹4.85 Cr AUM across NRE/NRO FDs, Axis Bluechip Mutual Fund SIPs, and ₹1.85 Cr Home Loan (Gurgaon).",
            key_discussion_topics=[
                "Daughter's UK tuition remittance and living expenses structure.",
                "Home loan rate reset and repo-spread benchmark review.",
                "Senior citizen doorstep banking for parents.",
            ],
            conversation_starter="Hello Rahul, Neha Kapoor here from Axis Bank. Kunal has briefed me thoroughly on our journey together over the past 7 years. I understand Ananya is preparing for her move to UCL in London, your parents in Gurgaon need doorstep assistance, and we have the home loan rate reset due this month. I have already initiated the overseas student remittance documentation so you won't have to restart anything. Let me take this forward together.",
            talking_points=[
                "Confirm UCL tuition deadline and provide pre-filled LRS documentation.",
                "Share the reduced rate reset options for the Gurgaon property.",
                "Confirm that Gurgaon branch lead has been assigned for doorstep parents' visit.",
            ],
            customer_priorities=[
                "Overseas Higher Education (Daughter Ananya attending UCL London)",
                "Home Loan Spread Review & Margin Concession (₹1.85 Cr loan)",
                "Family Banking & Senior Citizen Care (Parents Ashok & Savitri in DLF Gurgaon)",
            ],
            explicit_preferences=[
                "Strict contact window: Weekday evenings 6:30 PM – 8:30 PM IST only.",
                "Direct communication: WhatsApp for urgent messages, detailed email for calculations.",
                "No promotional tele-calling or mass SMS campaigns.",
            ],
            current_conversations=[
                "UCL tuition remittance documentation and A2 declaration formalities.",
                "Home loan repo-spread discount review prior to September 30 reset.",
            ],
            open_threads=[
                "Assigning dedicated officer from Gurgaon Sector 29 branch for parents' Form 15H collection.",
                "Verification of student visa & university offer letter for LRS limits.",
            ],
            customer_concerns=[
                "Sensitive to interest rate spread hikes; expects relationship pricing on Gurgaon home loan.",
                "Anxious about timely remittance for university fee deadline.",
            ],
            dont_repeat_items=[
                "Customer has already submitted KYC documents for Singapore hedge fund employment.",
                "Customer has already confirmed Ananya's university admission at UCL London.",
                "Customer has already explained his father's medical immobility requiring doorstep assistance.",
            ],
            important_context=[
                "Rahul is a senior hedge fund portfolio manager; treat him as a market peer with crisp numbers rather than generic retail pitches.",
                "Kunal Deshmukh built immense personal trust by resolving an overseas card issue in 2022; honoring commitments is essential.",
            ],
            synthesized_at="2026-09-02T14:30:00Z",
        ),
        feedback=CustomerFeedback(
            confirmed_at=None,
            customer_notes=None,
            corrected_items=[],
            has_verified=False,
        ),
    )

    c2 = CustomerRelationship(
        id="cust-burgundy-dr-sen",
        name="Dr. Ananya Sen",
        tier=ClientTier.BURGUNDY_PRIVATE,
        segment_description="Burgundy Private — Family Office & Ultra HNW",
        city="South Mumbai (Altamount Road)",
        account_number_masked="•••• 3190",
        aum_display="₹18.5 Cr ($2.2M USD)",
        tenure_years=11,
        avatar_color="from-rose-800 to-purple-950",
        previous_rm_name="Vikram Singhania",
        previous_rm_role="Director, Burgundy Private Client Group",
        transfer_reason="Resigned to join a venture capital partnership",
        new_rm_name="Aditya Mehta",
        new_rm_role="Vice President, Burgundy Private Wealth",
        new_rm_phone="+91 99200 88123",
        new_rm_email="aditya.mehta@axisbank.com",
        status=TransitionStatus.INITIATED,
        transition_date="2026-09-05",
        interactions=[
            CRMInteraction(
                id="int-201",
                date="2026-08-28",
                channel="In-Person Lunch",
                rm_name="Vikram Singhania",
                summary="Discussed allocation of ₹3.5 Cr proceeds from healthtech angel exit. Exploring Axis Burgundy Private Discretionary PMS (Multi-Cap Opportunities). Client wants capital protection with moderate equity upside. Vikram promised to deliver a customized PMS proposal before Sept 20.",
                tags=["PMS", "Liquidity Event", "Private Wealth", "Angel Exit"],
            ),
            CRMInteraction(
                id="int-202",
                date="2026-08-10",
                channel="WhatsApp Note",
                rm_name="Vikram Singhania",
                summary="Dr. Sen mentioned her surgical schedule is intense between Mon-Fri (7 AM to 4 PM). Strictly do not call during hospital hours. Saturday mornings between 10 AM - 11:30 AM are ideal for wealth discussions.",
                tags=["Communication Rules", "Surgical Schedule", "High Respect"],
            ),
            CRMInteraction(
                id="int-203",
                date="2026-07-14",
                channel="Branch Meeting",
                rm_name="Vikram Singhania",
                summary="Discussed Sen Family Trust deed registration with Axis Trustee Services. Client needs final legal opinion on inheritance tax sheltering. Vikram committed that Axis Trustee legal counsel would review the deed clauses.",
                tags=["Trustee Services", "Estate Planning", "Succession"],
            ),
        ],
        action_items=[
            TransitionActionItem(
                id="act-201",
                title="Burgundy Private PMS Allocation Proposal",
                description="Prepare customized mandate document for ₹3.5 Cr discretionary PMS investment with drawdown schedule.",
                category="Wealth Allocation",
                priority=ActionPriority.HIGH,
                status=ActionStatus.PENDING,
                sla_date="2026-09-20",
                assigned_to="Aditya Mehta",
            ),
            TransitionActionItem(
                id="act-202",
                title="Axis Trustee Legal Opinion Follow-Up",
                description="Obtain formal legal sign-off on Sen Family Trust clauses from Axis Trustee Services and deliver to client.",
                category="Estate & Trust",
                priority=ActionPriority.HIGH,
                status=ActionStatus.IN_PROGRESS,
                sla_date="2026-09-28",
                assigned_to="Aditya Mehta",
            ),
        ],
        commitments=[
            CommitmentItem(
                id="com-201",
                title="Custom Discretionary PMS Mandate Proposal",
                details="Vikram promised to deliver a tailored Discretionary Portfolio Management proposal for ₹3.5 Cr secondary exit proceeds by Sept 20.",
                committed_by="Vikram Singhania",
                committed_on="2026-08-28",
                commitment_type=CommitmentType.CONFIRMED_COMMITMENT,
                status=CommitmentStatus.PENDING,
                urgency=ActionPriority.HIGH,
                source_interaction_id="int-201",
                evidence_snippet="Vikram promised to deliver a customized PMS proposal before Sept 20.",
            ),
            CommitmentItem(
                id="com-202",
                title="Axis Trustee Legal Opinion on Family Trust Deed",
                details="Committed to having Axis Trustee in-house counsel review the inheritance tax sheltering clauses for Sen Family Trust.",
                committed_by="Vikram Singhania",
                committed_on="2026-07-14",
                commitment_type=CommitmentType.CONFIRMED_COMMITMENT,
                status=CommitmentStatus.IN_PROGRESS,
                urgency=ActionPriority.HIGH,
                source_interaction_id="int-203",
                evidence_snippet="Vikram committed that Axis Trustee legal counsel would review the deed clauses.",
            ),
        ],
        timeline=[
            RelationshipTimelineEvent(
                id="time-201",
                year="2015",
                date_display="March 2015",
                title="Inaugural Private Banking Relationship",
                description="Onboarded to Axis Private Banking with medical clinic operating accounts and personal wealth portfolio.",
                category="Relationship Inception",
                source_channel="Private Wealth Desk",
            ),
            RelationshipTimelineEvent(
                id="time-202",
                year="2020",
                date_display="November 2020",
                title="Burgundy Private Upgrade & AIF Allocation",
                description="Portfolio crossed ₹10 Cr; upgraded to Burgundy Private with specialized Cat II Alternate Investment Fund allocation.",
                category="Wealth & Investment",
                source_channel="Portfolio Review",
            ),
            RelationshipTimelineEvent(
                id="time-203",
                year="2024",
                date_display="December 2024",
                title="Family Office Structuring & Trustee Advisory",
                description="Initiated creation of Sen Family Trust with Axis Trustee Services for multi-generational wealth preservation.",
                category="Estate Planning",
                source_channel="Consultation",
            ),
            RelationshipTimelineEvent(
                id="time-204",
                year="2026",
                date_display="August 2026",
                title="HealthTech Angel Exit Liquidity Event (₹3.5 Cr)",
                description="Secondary share sale proceeds deposited in Axis Burgundy account; discretionary mandate initiated.",
                category="Liquidity Event",
                source_channel="Direct Credit",
            ),
            RelationshipTimelineEvent(
                id="time-205",
                year="2026",
                date_display="September 2026",
                title="RM Transition: Vikram Singhania to Aditya Mehta",
                description="Vikram departs for venture capital fund; Aditya Mehta assigned under Saathi Continuity Engine.",
                category="Transition",
                source_channel="Saathi System",
            ),
        ],
        contradictions=[],
        facts=[
            CustomerFact(
                id="fact-201",
                statement="Founder & Chief of Surgical Oncology at South Mumbai hospital; ₹3.5 Cr liquidity event from HealthTech angel exit awaiting deployment.",
                category="Professional & Wealth",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-08-28",
            ),
            CustomerFact(
                id="fact-202",
                statement="Hospital operating theatre blackout: Strictly unavailable Mon–Fri 7:00 AM – 4:00 PM.",
                category="Preferences",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-08-10",
            ),
            CustomerFact(
                id="fact-203",
                statement="Sen Family Trust is being structured with Axis Trustee Services for estate planning and second-generation succession.",
                category="Estate & Succession",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-07-14",
            ),
        ],
        health=RelationshipHealth(
            level=HealthLevel.IMMEDIATE_ATTENTION,
            headline="Immediate Attention: ₹3.5 Cr Discretionary PMS Proposal & Trust Legal Sign-Off Pending",
            reasons=[
                "₹3.5 Cr secondary exit proceeds currently sitting in savings account yielding low return.",
                "Customized PMS proposal committed by Vikram is due on Sept 20.",
                "RM Vikram Singhania resigned suddenly; risk of competitor family offices poaching relationship.",
            ],
        ),
        pre_call_brief=PreCallBriefing(
            who_is_customer="Dr. Ananya Sen, 11-year Burgundy Private marquee client (₹18.5 Cr AUM). Renowned surgical oncologist and healthtech investor.",
            what_matters=[
                "Deploying ₹3.5 Cr angel exit proceeds into conservative capital-protection equity PMS.",
                "Completing legal registration of Sen Family Trust.",
                "Absolute respect for her intensive surgical schedule.",
            ],
            current_discussions=[
                "Axis Burgundy Private Discretionary PMS allocation.",
                "Axis Trustee Services legal review of trust deed.",
            ],
            what_we_owe=[
                "Deliver customized PMS allocation memo by Sept 20 (Promised by Vikram).",
                "Finalize Axis Trustee legal opinion on inheritance sheltering.",
            ],
            unresolved_issues=[
                "Client was caught off-guard by Vikram's sudden resignation; requires immediate reassurance from senior management.",
            ],
            follow_up_items=[
                "Schedule 20-minute Saturday morning catchup at 10 AM to present PMS proposal.",
                "Deliver printed executive summary of trustee opinion.",
            ],
            sensitive_nuances=[
                "Strict 'Do Not Disturb' Monday to Friday 7:00 AM to 4:00 PM. Never call her mobile during surgical hours.",
                "Only connect on Saturday between 10:00 AM – 11:30 AM or via discrete WhatsApp message.",
            ],
            recommended_approach="Reach out via concise WhatsApp message on Friday afternoon requesting a brief call Saturday at 10 AM. Introduce Aditya Mehta warmly, state that the ₹3.5 Cr PMS memo is finalized, and assure her of leadership continuity.",
        ),
        management_summary=ManagementSummary(
            client_snapshot="Dr. Ananya Sen is an Ultra HNW Burgundy Private pillar (₹18.5 Cr AUM, 11-year relationship). Top 5 client for South Mumbai Private Banking hub.",
            aum_and_tier="₹18.5 Cr AUM ($2.2M USD) • Burgundy Private Tier • Ultra High Net Worth Individuals",
            active_opportunities=[
                "₹3.5 Cr Discretionary PMS mandate onboarding.",
                "Family office custodial account creation via Axis Trustee Services.",
            ],
            risk_and_unresolved=[
                "High churn vulnerability due to Vikram's departure to VC firm.",
                "Competitor private banks (Kotak, Julius Baer) actively targeting South Mumbai medical pioneers.",
            ],
            rm_handover_status="High priority handover. Handover dashboard active, briefing reviewed by Aditya Mehta.",
            executive_notes="Group Head Private Banking should make a co-call with Aditya within the first 14 days of transition.",
        ),
        brief=RelationshipBrief(
            client_sentiment="Ultra-HNW medical pioneer. Deep emotional attachment to 11-year relationship with Axis. Sensitive to interruptions during medical commitments.",
            executive_summary="Dr. Sen is a renowned surgical oncologist and medical tech founder with ₹18.5 Cr AUM. Following a recent ₹3.5 Cr liquidity event, she is evaluating discretionary PMS and formalizing estate succession via Axis Trustee Services. Respect for her demanding schedule and discreet, proactive execution are paramount.",
            family_and_lifestage=[
                "Founder of MedTech startup with recent secondary exit.",
                "Structuring Sen Family Trust for second-generation succession.",
            ],
            preferences_and_nuances=[
                "Strict 'Do Not Disturb' policy Mon–Fri 7:00 AM – 4:00 PM due to hospital OT schedule.",
                "Saturday mornings (10:00 AM – 11:30 AM) preferred for wealth reviews.",
                "Prefers concise executive summaries over verbose product brochures.",
            ],
            active_portfolio_summary="₹18.5 Cr AUM spanning Fixed Income, Alternate Investment Funds (AIF Cat II), and Direct Equity.",
            key_discussion_topics=[
                "₹3.5 Cr PMS Mandate allocation & fee structure.",
                "Sen Family Trust legal registration with Axis Trustee Services.",
            ],
            conversation_starter="Good morning Dr. Sen, Aditya Mehta here from Axis Burgundy Private. Vikram shared a thorough overview of your 11-year relationship with Axis before his transition. I am fully updated on the ₹3.5 Cr PMS allocation from your recent exit and the Axis Trustee opinion for your family trust. Because I know your surgery schedule takes absolute precedence during weekdays, I would be glad to connect briefly this Saturday at 10 AM or whenever convenient for you.",
            talking_points=[
                "Acknowledge the 11-year trust with Axis Burgundy Private.",
                "Present the completed legal opinion on the family trust.",
                "Review the draft PMS portfolio allocation at her convenience.",
            ],
            customer_priorities=[
                "Wealth Preservation & Discretionary PMS Allocation (₹3.5 Cr)",
                "Estate Planning & Family Trust Registration (Sen Family Trust)",
                "Discreet and Schedule-Sensitive Communication",
            ],
            explicit_preferences=[
                "Strict OT blackout: Never call weekdays 7:00 AM – 4:00 PM.",
                "Preferred conversation window: Saturday 10:00 AM – 11:30 AM.",
                "Concise 1-page briefs; no generic sales pitches.",
            ],
            current_conversations=[
                "Custom Discretionary PMS allocation memo for angel exit liquidity.",
                "Tax sheltering clauses in trust deed via Axis Trustee Services.",
            ],
            open_threads=[
                "Obtaining formal written legal sign-off from Axis Trustee.",
                "Finalizing fee schedule and asset allocation breakdown for PMS.",
            ],
            customer_concerns=[
                "Dislikes RM turnover; expects seamless continuity without having to re-explain her family trust structure.",
            ],
            dont_repeat_items=[
                "Customer has already explained the angel exit share sale structure.",
                "Customer has already provided beneficiary details for the Sen Family Trust.",
                "Customer has repeatedly stated her weekday surgical blackout.",
            ],
            important_context=[
                "Dr. Sen is one of India's preeminent surgical oncologists. Respect for her time and professional dignity is non-negotiable.",
            ],
            synthesized_at="2026-09-05T11:00:00Z",
        ),
        feedback=CustomerFeedback(
            confirmed_at=None,
            customer_notes=None,
            corrected_items=[],
            has_verified=False,
        ),
    )

    c3 = CustomerRelationship(
        id="cust-wealth-vikram-malhotra",
        name="Vikramaditya Malhotra",
        tier=ClientTier.WEALTH,
        segment_description="Axis Wealth & Commercial Banking",
        city="New Delhi (Aerocity / Vasant Vihar)",
        account_number_masked="•••• 7104",
        aum_display="₹7.20 Cr ($860K USD)",
        tenure_years=5,
        avatar_color="from-teal-700 to-slate-900",
        previous_rm_name="Pooja Bansal",
        previous_rm_role="AVP, Commercial & Wealth Banking",
        transfer_reason="Relocated to Axis Bangalore Innovation Hub",
        new_rm_name="Rajesh Verma",
        new_rm_role="Director, Wealth & Enterprise Client Solutions",
        new_rm_phone="+91 98110 32901",
        new_rm_email="rajesh.verma@axisbank.com",
        status=TransitionStatus.CUSTOMER_CONFIRMED,
        transition_date="2026-08-25",
        interactions=[
            CRMInteraction(
                id="int-301",
                date="2026-08-20",
                channel="Coffee Meeting (Aerocity)",
                rm_name="Pooja Bansal",
                summary="Vikram is expanding his logistics tech firm to Dubai (DIFC). Needs multi-currency corporate travel card for 8 executives and credit line enhancement of ₹2.5 Cr for export receivables. Pooja promised 8 forex cards delivered by Sept 8.",
                tags=["Export Finance", "Dubai Expansion", "Forex Card", "SME"],
            ),
            CRMInteraction(
                id="int-302",
                date="2026-08-01",
                channel="Email Summary",
                rm_name="Pooja Bansal",
                summary="High-speed communicator. Prefers bullet points and immediate turnarounds. Family: son Kabir is preparing for US college entrance exams.",
                tags=["Preferences", "Fast Turnaround", "Family"],
            ),
        ],
        action_items=[
            TransitionActionItem(
                id="act-301",
                title="Corporate Multi-Currency Forex Card Issuance",
                description="Deliver 8 multi-currency cards with preloaded AED and USD limits for executive team Dubai delegation.",
                category="Forex & Commercial",
                priority=ActionPriority.HIGH,
                status=ActionStatus.COMPLETED,
                sla_date="2026-09-08",
                assigned_to="Rajesh Verma",
            ),
            TransitionActionItem(
                id="act-302",
                title="Commercial Credit Line (₹2.5 Cr) Sanction Letter",
                description="Coordinate with commercial risk committee for enhanced overdraft facility against export invoices.",
                category="Credit Enhancement",
                priority=ActionPriority.HIGH,
                status=ActionStatus.IN_PROGRESS,
                sla_date="2026-09-15",
                assigned_to="Rajesh Verma",
            ),
        ],
        commitments=[
            CommitmentItem(
                id="com-301",
                title="Delivery of 8 Multi-Currency Forex Cards",
                details="Pooja promised that 8 corporate travel cards with preloaded limits would be delivered to Aerocity headquarters by Sept 8.",
                committed_by="Pooja Bansal",
                committed_on="2026-08-20",
                commitment_type=CommitmentType.CONFIRMED_COMMITMENT,
                status=CommitmentStatus.COMPLETED,
                urgency=ActionPriority.HIGH,
                source_interaction_id="int-301",
                evidence_snippet="Pooja promised 8 forex cards delivered by Sept 8.",
            ),
            CommitmentItem(
                id="com-302",
                title="₹2.5 Cr Overdraft Limit Enhancement for Export Receivables",
                details="Discussed enhancement of trade credit limit for Dubai expansion. Pooja agreed to present file to credit committee; discussed as in-process requirement, not an unconditional guarantee.",
                committed_by="Pooja Bansal",
                committed_on="2026-08-20",
                commitment_type=CommitmentType.DISCUSSED_POSSIBILITY,
                status=CommitmentStatus.IN_PROGRESS,
                urgency=ActionPriority.HIGH,
                source_interaction_id="int-301",
                evidence_snippet="Credit line enhancement of ₹2.5 Cr for export receivables discussed; pending credit committee sanction.",
            ),
        ],
        timeline=[
            RelationshipTimelineEvent(
                id="time-301",
                year="2021",
                date_display="August 2021",
                title="Enterprise & Commercial Account Established",
                description="Opened corporate current accounts and personal wealth relationship for logistics tech enterprise.",
                category="Relationship Inception",
                source_channel="Corporate Banking",
            ),
            RelationshipTimelineEvent(
                id="time-302",
                year="2023",
                date_display="April 2023",
                title="Export Credit Overdraft Facility Sanctioned",
                description="Sanctioned ₹5 Cr working capital overdraft facility for North American trade routes.",
                category="Credit & Lending",
                source_channel="Risk Committee",
            ),
            RelationshipTimelineEvent(
                id="time-303",
                year="2025",
                date_display="November 2025",
                title="Personal Wealth Expansion (₹7.2 Cr AUM)",
                description="Invested ₹2.5 Cr in equity PMS and booked ₹1.5 Cr in corporate fixed deposits.",
                category="Wealth & Investment",
                source_channel="Annual Review",
            ),
            RelationshipTimelineEvent(
                id="time-304",
                year="2026",
                date_display="August 2026",
                title="Dubai DIFC Expansion & RM Handover to Rajesh Verma",
                description="Pooja Bansal transferred to Bangalore; Rajesh Verma assumed relationship.",
                category="Transition",
                source_channel="Saathi System",
            ),
        ],
        contradictions=[],
        facts=[
            CustomerFact(
                id="fact-301",
                statement="Founder & MD of logistics technology enterprise expanding regional hub to Dubai DIFC.",
                category="Business Expansion",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-08-20",
            ),
            CustomerFact(
                id="fact-302",
                statement="High-speed communicator: Expects concise bullet points and rapid turnaround.",
                category="Preferences",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-08-01",
            ),
            CustomerFact(
                id="fact-303",
                statement="Son Kabir in Grade 12 preparing for US SAT exam; coaching fee wire transfer needed.",
                category="Family & Education",
                status=CustomerFactStatus.CONFIRMED,
                last_updated="2026-08-27",
            ),
        ],
        health=RelationshipHealth(
            level=HealthLevel.STABLE,
            headline="Stable: Customer Confirmed Context & Primary SLAs Dispatched",
            reasons=[
                "Customer verified and confirmed relationship context via Saathi portal.",
                "8 Corporate multi-currency forex cards successfully delivered to Aerocity office.",
                "₹2.5 Cr credit line enhancement paper submitted to commercial credit committee.",
            ],
        ),
        pre_call_brief=PreCallBriefing(
            who_is_customer="Vikramaditya Malhotra, 5-year Wealth & Commercial client (₹7.2 Cr personal AUM + ₹15 Cr annual commercial turnover). Logistics tech founder.",
            what_matters=[
                "Speed, agility, and quick execution for his corporate Dubai expansion.",
                "Seamless handling of both company export facilities and personal investments.",
            ],
            current_discussions=[
                "Dubai DIFC entity forex solutions and ₹2.5 Cr credit line enhancement.",
                "Son Kabir's US SAT wire transfer to Singapore test center.",
            ],
            what_we_owe=[
                "Update on ₹2.5 Cr commercial credit committee sanction letter.",
                "Assistance with direct coaching fee wire transfer for Kabir.",
            ],
            unresolved_issues=[
                "Credit committee approval pending for the ₹2.5 Cr enhancement.",
            ],
            follow_up_items=[
                "Confirm that executive team received the 8 multi-currency cards.",
                "Provide expected date for credit sanction letter.",
            ],
            sensitive_nuances=[
                "Extremely fast-paced. Do not engage in lengthy small talk; present status in numbered bullet points.",
            ],
            recommended_approach="Send a crisp 3-bullet WhatsApp update confirming delivery of the 8 cards and current committee progress on the credit enhancement. Follow up with a quick 5-minute call.",
        ),
        management_summary=ManagementSummary(
            client_snapshot="Vikramaditya Malhotra represents an agile high-growth commercial and wealth account (₹7.2 Cr personal AUM, ₹15 Cr commercial turnover).",
            aum_and_tier="₹7.20 Cr AUM ($860K USD) • Axis Wealth & Commercial • Emerging Corporate",
            active_opportunities=[
                "Dubai DIFC corporate accounts and treasury forex flows.",
                "Family wealth expansion upon commercial liquidity milestones in FY27.",
            ],
            risk_and_unresolved=[
                "Need to ensure commercial credit committee does not delay the ₹2.5 Cr enhancement.",
            ],
            rm_handover_status="Handover validated and confirmed by client. Rajesh Verma in active management.",
            executive_notes="Model example of smooth Saathi continuity. Retain velocity of service.",
        ),
        brief=RelationshipBrief(
            client_sentiment="Fast-moving growth entrepreneur. Values banking agility, quick TAT, and unified handling of personal wealth and business accounts.",
            executive_summary="Vikramaditya is the founder of a high-growth logistics technology enterprise scaling into the GCC. He balances active personal investments (₹7.2 Cr AUM) with heavy commercial banking needs. Core requirements are export credit enhancement and smooth forex solutions for his team.",
            family_and_lifestage=[
                "Son Kabir in grade 12, preparing for US university admissions.",
                "Business expanding into Dubai International Financial Centre (DIFC).",
            ],
            preferences_and_nuances=[
                "Direct, concise bullet-point communications; prefers rapid email/WhatsApp responses.",
                "Frequent flyer between Delhi, Dubai, and Bangalore.",
            ],
            active_portfolio_summary="₹7.2 Cr personal AUM + ₹15 Cr commercial banking turnover through Axis current accounts.",
            key_discussion_topics=[
                "₹2.5 Cr credit limit enhancement for export receivables.",
                "Executive multi-currency forex cards for Dubai delegation.",
            ],
            conversation_starter="Hello Vikram, Rajesh Verma here. Pooja briefed me on our 5-year partnership before her move to Bangalore. I know you're in the midst of the Dubai DIFC expansion and the export credit limit enhancement is on critical path. I've already confirmed the multi-currency cards are dispatched, and I'm pushing the credit committee on the sanction letter today.",
            talking_points=[
                "Forex cards delivered to Aerocity office.",
                "Status update on ₹2.5 Cr credit enhancement.",
                "Schedule quick 10-minute catchup at Aerocity.",
            ],
            customer_priorities=[
                "Corporate Overseas Expansion (Dubai DIFC entity & multi-currency cards)",
                "Commercial Working Capital (₹2.5 Cr export credit line)",
                "Family Education (Son Kabir's US university preparations)",
            ],
            explicit_preferences=[
                "Communication style: Short bullet points only; direct and fast.",
                "Preferred channels: WhatsApp for instant updates, email for formal sanctions.",
            ],
            current_conversations=[
                "Corporate multi-currency card distribution.",
                "Commercial credit line enhancement with risk committee.",
            ],
            open_threads=[
                "Risk committee sanction memo for ₹2.5 Cr overdraft.",
                "Coaching fee wire transfer for son Kabir.",
            ],
            customer_concerns=[
                "TAT sensitivity: any delay in commercial banking directly impacts his business operations.",
            ],
            dont_repeat_items=[
                "Customer has already submitted the Dubai trade contracts and financials.",
                "Customer has already provided executive passport lists for forex cards.",
            ],
            important_context=[
                "Entrepreneur with low tolerance for bureaucratic delays. Solving commercial bottlenecks cements personal wealth loyalty.",
            ],
            synthesized_at="2026-08-26T09:15:00Z",
        ),
        feedback=CustomerFeedback(
            confirmed_at="2026-08-27T10:14:00Z",
            customer_notes="Confirmed. Please also note that Kabir's SAT coaching fees might require a direct wire transfer to Singapore test center by next Wednesday.",
            corrected_items=["Added son Kabir's test fee wire transfer deadline."],
            has_verified=True,
        ),
    )

    return {
        c1.id: c1,
        c2.id: c2,
        c3.id: c3,
    }
